### ISSUE TITLE
Enterprise SDK is not available through maven central

### ISSUE THREAD

**Issue by amkonarska** [TeleSign/java_telesign_enterprise#4]
Hi!

Were you considering putting enterprise SDK in maven central (like the regular one)? It would be easier to use then.

Thanks!
Aleksandra Konarska

**Comment by adohertyTS** [comment]
Hi @amkonarska, sorry for the late reply, but I am the incoming product manager for this SDK and, yes, we are in progress working on putting this SDK on Maven Central. We expect that work to be completed this quarter.

**Comment by adohertyTS** [comment]
Hi @amkonarska, just a heads up that we added this SDK to Maven Central Repository on July 25, 2024:
https://central.sonatype.com/artifact/com.telesign.enterprise/telesignenterprise/versions
